name: Mend SAST CLI Scan

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Mend CLI Scan
      env:
        #SAST
        MEND_SAST_SERVER_URL: https://saas-eu.mend.io/sast
        MEND_SAST_API_TOKEN: ${{secrets.MEND_SAST_API}}
        MEND_SAST_ORGANIZATION: ${{secrets.MEND_SAST_ORGANIZATION}}
        MEND_SAST_THRESHOLD_HIGH: 5
      run: |
        echo Downloading Mend CLI
        curl -LJO https://downloads.mend.io/production/unified/latest/linux_amd64/mend && chmod +x mend
        echo Start Mend CLI scan
        ./mend sast
